sudo: false 
language: android
before_install:  
 - rvm install ruby --latest
env: 
  global: 
  # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=5
android:
  components:
    - platform-tools
    - extra-android-m2repository
    - build-tools-22.0.1
    - android-22
    - sys-img-armeabi-v7a-android-22
# whitelist
branches:
  - travis-ci-branch
before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
   #- gem update --system 2.5.1
  - gem install calabash-android
  - gem install cucumber
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator  
script:  
  - adb kill-server
  - adb start-server
  - adb devices
  - adb install -r app-debug.apk
  - calabash-android run CalabashAutomation/app-debug.apk CalabashAutomation/features/Wardarobe.feature
